/*
 * This file is part of OpenTTD.
 * OpenTTD is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
 * OpenTTD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with OpenTTD. If not, see <https://www.gnu.org/licenses/old-licenses/gpl-2.0>.
 */

/** @file modular_airport_tile_name.cpp Names for modular airport tile pieces. */

#include "stdafx.h"
#include "modular_airport_tile_name.h"

#include "table/airporttile_ids.h"
#include "table/strings.h"

#include "safeguards.h"

static constexpr StringID _modular_tile_names[] = {
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_APRON
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_APRON_FENCE_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_APRON_FENCE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_STAND,             // APT_STAND
	STR_LAI_STATION_DESCRIPTION_AIRPORT_APRON_EDGE,            // APT_APRON_W
	STR_LAI_STATION_DESCRIPTION_AIRPORT_APRON_EDGE,            // APT_APRON_S
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TAXIWAY_CROSS,     // APT_APRON_VER_CROSSING_S
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TAXIWAY_CROSS,     // APT_APRON_HOR_CROSSING_W
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TAXIWAY,           // APT_APRON_VER_CROSSING_N
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TAXIWAY_CROSS,     // APT_APRON_HOR_CROSSING_E
	STR_LAI_STATION_DESCRIPTION_AIRPORT_APRON_EDGE,            // APT_APRON_E
	STR_LAI_STATION_DESCRIPTION_AIRPORT_APRON_EDGE,            // APT_APRON_N
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TAXIWAY,           // APT_APRON_HOR
	STR_LAI_STATION_DESCRIPTION_AIRPORT_APRON_EDGE,            // APT_APRON_N_FENCE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY,            // APT_RUNWAY_1
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY,            // APT_RUNWAY_2
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY,            // APT_RUNWAY_3
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY,            // APT_RUNWAY_4
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_END,        // APT_RUNWAY_END_FENCE_SE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TERMINAL_ALT,      // APT_BUILDING_2
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TOWER,             // APT_TOWER_FENCE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TERMINAL_ROUND,    // APT_ROUND_TERMINAL
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TERMINAL_OTHER,    // APT_BUILDING_3
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TERMINAL,          // APT_BUILDING_1
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_HANGAR,            // APT_DEPOT_SE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_STAND_1,           // APT_STAND_1
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_STAND_PIER,        // APT_STAND_PIER_NE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_PIER_NW_NE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_PIER
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_EMPTY,             // APT_EMPTY
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_EMPTY,             // APT_EMPTY_FENCE_NE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RADAR_GRASS,       // APT_RADAR_GRASS_FENCE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RADIO_TOWER,       // APT_RADIO_TOWER_FENCE_NE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_SMALL_TERMINAL_3,  // APT_SMALL_BUILDING_3
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_SMALL_TERMINAL_3,  // APT_SMALL_BUILDING_2
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_SMALL_TERMINAL_3,  // APT_SMALL_BUILDING_1
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_GRASS,             // APT_GRASS_FENCE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_GRASS,             // APT_GRASS_2
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_GRASS,             // APT_GRASS_1
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_GRASS,             // APT_GRASS_FENCE_NE_FLAG
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_SMALL_NEAR, // APT_RUNWAY_SMALL_NEAR_END
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_SMALL_MID,  // APT_RUNWAY_SMALL_MIDDLE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_SMALL_FAR,  // APT_RUNWAY_SMALL_FAR_END
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_SMALL_HANGAR,      // APT_SMALL_DEPOT_SE
	STR_AIRPORT_HELIPORT,                                      // APT_HELIPORT
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_END,        // APT_RUNWAY_END
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY,            // APT_RUNWAY_5
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_TOWER,             // APT_TOWER
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_APRON_FENCE_NE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_END,        // APT_RUNWAY_END_FENCE_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY,            // APT_RUNWAY_FENCE_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RADAR,             // APT_RADAR_FENCE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RADAR,             // APT_RADAR_FENCE_NE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_HELIPAD,           // APT_HELIPAD_1
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_HELIPAD,           // APT_HELIPAD_2_FENCE_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_HELIPAD,           // APT_HELIPAD_2
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_APRON_FENCE_NE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_END,        // APT_RUNWAY_END_FENCE_NW_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_END,        // APT_RUNWAY_END_FENCE_SE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_END,        // APT_RUNWAY_END_FENCE_NE_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_RUNWAY_END,        // APT_RUNWAY_END_FENCE_NE_SE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_HELIPAD,           // APT_HELIPAD_2_FENCE_NE_SE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_APRON_FENCE_SE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_LOW_TERMINAL,      // APT_LOW_BUILDING_FENCE_N
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_LOW_TERMINAL,      // APT_LOW_BUILDING_FENCE_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_APRON_FENCE_SE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_PLAIN_H,           // APT_HELIPAD_3_FENCE_SE_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_PLAIN_H,           // APT_HELIPAD_3_FENCE_NW_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_PLAIN_H,           // APT_HELIPAD_3_FENCE_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_LOW_TERMINAL,      // APT_LOW_BUILDING
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON,             // APT_APRON_FENCE_NE_SE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON_HALF_E,      // APT_APRON_HALF_EAST
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APRON_HALF_W,      // APT_APRON_HALF_WEST
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_FLAG_GRASS,        // APT_GRASS_FENCE_NE_FLAG_2
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_HANGAR,            // APT_DEPOT_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_HANGAR,            // APT_DEPOT_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_HANGAR,            // APT_DEPOT_NE
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_SMALL_HANGAR,      // APT_SMALL_DEPOT_SW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_SMALL_HANGAR,      // APT_SMALL_DEPOT_NW
	STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_SMALL_HANGAR,      // APT_SMALL_DEPOT_NE
};
static_assert(lengthof(_modular_tile_names) == APT_END);

/**
 * Get the player-facing name of a modular airport tile piece.
 *
 * A converted stock airport can contain visual variants which the modular
 * builder does not place directly. Name those as the closest builder concept,
 * while retaining distinctions that are useful when inspecting the layout.
 * @param piece_type AirportTiles value stored in ModularAirportTileData.
 * @return Name of the piece, or STR_NULL when the value is not recognised.
 */
StringID GetModularAirportTileName(ModularAirportPieceID piece_type)
{
	switch (piece_type) {
		case APT_MODULAR_FIRE_STATION: return STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_FIRE_STATION;
		case APT_MODULAR_CARGO_TERMINAL: return STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_CARGO_TERMINAL;
		case APT_MODULAR_FUEL_FARM: return STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_FUEL_FARM;
		case APT_MODULAR_APPROACH_LIGHTS: return STR_STATION_BUILD_MODULAR_AIRPORT_PIECE_APPROACH_LIGHTS;
		default: break;
	}
	if (piece_type >= lengthof(_modular_tile_names)) return STR_NULL;
	return _modular_tile_names[piece_type];
}
